### ISSUE TITLE
Move plan parameter deserialization is broken

### ISSUE THREAD

**Issue by callumforrester** [DiamondLightSource/blueapi#119]
The move plan cannot process it's arguments following the move to pydantic. It gives the following error:
```shell
ERROR:blueapi.worker.reworker:1 validation error for ParsingModel[group]
__root__ -> moves
  'int' object is not subscriptable (type=type_error)
Traceback (most recent call last):
  File "/home/vid18871/projects/blueapi/src/blueapi/worker/reworker.py", line 94, in _cycle
    self._current.task.do_task(self._ctx)
  File "/home/vid18871/projects/blueapi/src/blueapi/worker/task.py", line 45, in do_task
    """
  File "/home/vid18871/projects/blueapi/src/blueapi/worker/task.py", line 66, in _lookup_params
    sanitized_params = lookup_params(ctx, plan, self.params)
  File "/home/vid18871/projects/blueapi/venv/lib/python3.8/site-packages/pydantic/tools.py", line 38, in parse_obj_as
    return model_type(__root__=obj).__root__
  File "/home/vid18871/projects/blueapi/venv/lib/python3.8/site-packages/pydantic/main.py", line 341, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 1 validation error for ParsingModel[group]
__root__ -> moves
  'int' object is not subscriptable (type=type_error)
```

**Comment by tpoliaw** [comment]
Steps to reproduce:
* Install blueapi via steps in docs [here](https://diamondlightsource.github.io/blueapi/main/developer/tutorials/dev-install.html#install-dependencies)
* Run `python -m blueap worker` to run the server locally
* Run `python -m blueapi controller run move -p '{"moves": {"foo": 23}}'` (from another terminal) to request a move.
