### ISSUE TITLE
Service does not gracefully start or shut down if activemq not available

### ISSUE THREAD

**Issue by rosesyrett** [DiamondLightSource/blueapi#220]
## Overview
Found out by accident that if I kill my activemq container but forget to shut down the blueapi REST service, the blueapi terminal just spams messages. Upon further testing I also found out, if there is no activemq, you cannot start the blueapi service either (although at least it doesn't spam messages). Steps to reproduce both cases are included below.

### On shutdown

To reproduce, run the following with an activemq instance working:
```
blueapi serve
```
You will see something like:
```
INFO:     Started server process [731956]
INFO:     Waiting for application startup.
INFO:blueapi.worker.multithread:Setting up event loop
INFO:blueapi.messaging.stomptemplate:Connecting...
INFO:blueapi.worker.multithread:Worker starting
INFO:blueapi.worker.reworker:Worker starting
INFO:blueapi.worker.reworker:Awaiting task
INFO:stomp.py:established connection to host localhost, port 61613
INFO:     Application startup complete.
INFO:     Uvicorn running on http://localhost:8000 (Press CTRL+C to quit)
```
Then terminate your activemq instance. You will see the following:
```
WARNING:blueapi.messaging.stomptemplate:Stomp connection lost, will attempt reconnection with policy StompReconnectPolicy(initial_delay=0.0, attempt_period=10.0)
INFO:blueapi.messaging.stomptemplate:Connecting...
INFO:stomp.py:established connection to host localhost, port 61613
ERROR:blueapi.messaging.stomptemplate:Reconnect failed
Traceback (most recent call last):
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 194, in _on_disconnected
    self.connect()
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 160, in connect
    self._conn.connect(wait=True)
  File "/venv/lib/python3.11/site-packages/stomp/connect.py", line 151, in connect
    Protocol11.connect(self, *args, **kwargs)
  File "/venv/lib/python3.11/site-packages/stomp/protocol.py", line 339, in connect
    self.transport.wait_for_connection()
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 318, in wait_for_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
INFO:blueapi.messaging.stomptemplate:Connecting...
WARNING:stomp.py:could not connect to host localhost, port 61613
```

This message will continue to repeat. If you attempt to press `Ctrl+C` to terminate the server, the following output is observed:
```
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:blueapi.worker.reworker:Attempting to stop worker
INFO:blueapi.messaging.stomptemplate:SENDING {"state": "IDLE", "taskStatus": null, "errors": [], "warnings": []} to /topic/public.worker.event
ERROR:blueapi.worker.reworker:
Traceback (most recent call last):
  File "/home/rose/Documents/projects/blueapi/src/blueapi/worker/reworker.py", line 130, in _cycle_with_error_handling
    self._cycle()
  File "/home/rose/Documents/projects/blueapi/src/blueapi/worker/reworker.py", line 154, in _cycle
    self._report_status()
  File "/home/rose/Documents/projects/blueapi/src/blueapi/worker/reworker.py", line 214, in _report_status
    self._worker_events.publish(event, correlation_id)
  File "/home/rose/Documents/projects/blueapi/src/blueapi/core/event.py", line 79, in publish
    callback(event, correlation_id)
  File "/home/rose/Documents/projects/blueapi/src/blueapi/service/handler.py", line 57, in <lambda>
    lambda event, correlation_id: self.message_bus.send(
                                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 115, in send
    self._send_str(
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 135, in _send_str
    self._conn.send(headers=headers, body=message, destination=destination)
  File "/venv/lib/python3.11/site-packages/stomp/protocol.py", line 402, in send
    self.send_frame(CMD_SEND, headers, body)
  File "/venv/lib/python3.11/site-packages/stomp/protocol.py", line 246, in send_frame
    self.transport.transmit(frame)
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 268, in transmit
    self.send(packed_frame)
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 628, in send
    raise exception.NotConnectedException()
stomp.exception.NotConnectedException
INFO:blueapi.worker.reworker:Stopped
INFO:blueapi.messaging.stomptemplate:Disconnecting...
INFO:blueapi.messaging.stomptemplate:Connecting...
WARNING:stomp.py:could not connect to host localhost, port 61613
WARNING:stomp.py:could not connect to host localhost, port 61613
WARNING:stomp.py:could not connect to host localhost, port 61613
ERROR:blueapi.messaging.stomptemplate:Reconnect failed
Traceback (most recent call last):
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 194, in _on_disconnected
    self.connect()
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 160, in connect
    self._conn.connect(wait=True)
  File "/venv/lib/python3.11/site-packages/stomp/connect.py", line 150, in connect
    self.transport.start()
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 108, in start
    self.attempt_connection()
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 807, in attempt_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
INFO:blueapi.messaging.stomptemplate:Connecting...
WARNING:stomp.py:could not connect to host localhost, port 61613
WARNING:stomp.py:could not connect to host localhost, port 61613
WARNING:stomp.py:could not connect to host localhost, port 61613
ERROR:blueapi.messaging.stomptemplate:Reconnect failed
Traceback (most recent call last):
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 194, in _on_disconnected
    self.connect()
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 160, in connect
    self._conn.connect(wait=True)
  File "/venv/lib/python3.11/site-packages/stomp/connect.py", line 150, in connect
    self.transport.start()
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 108, in start
    self.attempt_connection()
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 807, in attempt_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException
```

### On startup
If you don't have activemq running, the following output is observed:
```
(venv) root ➜ .../rose/Documents/projects/blueapi (main) $ blueapi serve
INFO:     Started server process [734356]
INFO:     Waiting for application startup.
INFO:blueapi.worker.multithread:Setting up event loop
INFO:blueapi.messaging.stomptemplate:Connecting...
INFO:blueapi.worker.multithread:Worker starting
INFO:blueapi.worker.reworker:Worker starting
INFO:blueapi.worker.reworker:Awaiting task
WARNING:stomp.py:could not connect to host localhost, port 61613
WARNING:stomp.py:could not connect to host localhost, port 61613
WARNING:stomp.py:could not connect to host localhost, port 61613
ERROR:    Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 204, in __aenter__
    return await anext(self.gen)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/rose/Documents/projects/blueapi/src/blueapi/service/main.py", line 16, in lifespan
    setup_handler(config)
  File "/home/rose/Documents/projects/blueapi/src/blueapi/service/handler.py", line 75, in setup_handler
    handler.start()
  File "/home/rose/Documents/projects/blueapi/src/blueapi/service/handler.py", line 47, in start
    self.message_bus.connect()
  File "/home/rose/Documents/projects/blueapi/src/blueapi/messaging/stomptemplate.py", line 160, in connect
    self._conn.connect(wait=True)
  File "/venv/lib/python3.11/site-packages/stomp/connect.py", line 150, in connect
    self.transport.start()
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 108, in start
    self.attempt_connection()
  File "/venv/lib/python3.11/site-packages/stomp/transport.py", line 807, in attempt_connection
    raise exception.ConnectFailedException()
stomp.exception.ConnectFailedException

ERROR:    Application startup failed. Exiting.
```

Trying to exit via carriage return (`Ctrl+C`) does nothing and the terminal just hangs.

**Comment by callumforrester** [comment]
What do you think we should do in these circumstances?
Before the REST API the message bus was vital to operation so it makes sense if we can't start without it, do we think this is still the case?

The reason it spams messages if activemq goes down is that it's trying to reconnect in case there is just a temporary outage. This made life a lot easier on the test rig because it meant we could restart ActiveMQ without also having to restart blueapi.

**Comment by RAYemelyanova** [comment]
Sure, I can understand that. I'm just imagining in a deployment situation, it might be annoying if activemq is actually down that blueapi spams greylog with messages.

**Comment by callumforrester** [comment]
Potentially, yes, but what would you prefer it do instead? Just try to reconnect silently?

**Comment by tpoliaw** [comment]
retry with a back-off? wait 1s then 2s then 3s, 5, 8 etc. If a request is received while the connection is still down, fail immediately.

>Before the REST API the message bus was vital to operation

It still is if you want data to be recorded somewhere, isn't it?

**Comment by callumforrester** [comment]
Back-off is sensible, would still be some log spam but substantially less, we could also tune the back-off period based on ActiveMQ outage statistics from prometheus which would be quite cool. What do you think @RAYemelyanova?

> It still is if you want data to be recorded somewhere, isn't it?

Yes, so answer is probably yes

**Comment by callumforrester** [comment]
That sounds good, thanks!

**Comment by tpoliaw** [comment]
>half of this bug is also that, on startup, I can't seem to shut down the service if activemq isn't running

`Ctrl-\` - sends `kill -9` to the running process and should handle whatever reconnect loop stomps gets stuck in

**Comment by RAYemelyanova** [comment]
Feels like Ctrl+C should also do the trick, considering the terminal also tells you that's what you need to do to shut it down.

**Comment by abbiemery** [comment]
I made a pr so you can use ```crtl+c``` if you loose activemq after you have started it, however I didn't implement the other case (of it not starting without an activemq instance) because you can just use ```ctrl+z``` and it involved a little bit of reorganising.(You can also use ```ctrl+z``` with the other case so the addition is pretty redundant). Also as @tpoliaw says, if you are stuck ```ctrl+\``` will get you out of it too.

**Comment by tpoliaw** [comment]
Does `Ctrl-z` kill the process or just leave it hanging in the background?

**Comment by abbiemery** [comment]
After much messing about, the case of using `ctrl+c` to shutdown bluapi if it was started without an active mq instance is probably worth shelving until the work on the sub-processes is merged. The issue came down to FastAPI not liking a crash loop back off within its lifespan method when setting up the handler, as opposed to once it had yielded after the setup. It was happy enough to raise an exception and allow exit once setup had "complete", but repeatedly trying to connect here yielded no space to keyboard interrupt. The subprocess work should change the running sufficiently that if it is not resolved by it, it would be worth re-assessing then.
