### ISSUE TITLE
Deserialisation errors in CLI client

### ISSUE THREAD

**Issue by tpoliaw** [DiamondLightSource/blueapi#280]
Now all messages/events are sent on the same topic, the cli needs to check the type of each message received. Currently running an example plan raises many exceptions similar to 

```
Exception in thread: 3 validation errors for ParsingModel[WorkerEvent]
__root__ -> state
  field required (type=value_error.missing)
__root__ -> doc
  extra fields not permitted (type=value_error.extra)
__root__ -> name
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/dls/athena/blueapi/src/blueapi/utils/thread_exception.py", line 31, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/dls/athena/blueapi/src/blueapi/messaging/stomptemplate.py", line 232, in _on_message
    sub.callback(frame)
  File "/dls/athena/blueapi/src/blueapi/messaging/stomptemplate.py", line 151, in wrapper
    value = parse_obj_as(obj_type, as_dict)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/tools.py", line 38, in pydantic.tools.parse_obj_as
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 3 validation errors for ParsingModel[WorkerEvent]
__root__ -> state
  field required (type=value_error.missing)
__root__ -> doc
  extra fields not permitted (type=value_error.extra)
__root__ -> name
  extra fields not permitted (type=value_error.extra)
```

**Comment by stan-dot** [comment]
@tpoliaw what are the steps to reproduce the issue?

**Comment by stan-dot** [comment]
potentially connected to #206

**Comment by tpoliaw** [comment]
Doesn't look like this is still an issue
