### ISSUE TITLE
Scan plan validation does not allow nested devices

### ISSUE THREAD

**Issue by paula-mg** [DiamondLightSource/blueapi#403]
Unsure if this is the correct repository so happy to re-raise.

When I have a nested device (e.g. `sample_stage.x`) and I try to run a scan with it, I get a validation error. Either blueapi or the plan itself does not seem to like the `a.b` syntax, even thought it is supposed to support arbitrarily-nested devices.

See blueapi log below:
```shell
DEBUG:bluesky:Stopping run '365bc8ea-0dea-442f-848d-17207a826d1a'
ERROR:bluesky:Failed to close run <bluesky.bundlers.RunBundler object at 0x7fd69ed22690>.
INFO:bluesky.RE.state:Change state on <bluesky.run_engine.RunEngine object at 0x7fd608fc0ed0> from 'running' -> 'idle'
INFO:blueapi.messaging.stomptemplate:SENDING {"state": "IDLE", "task_status": {"task_id": "8c7fc10c-c4f9-4423-8bd1-15544f63f473", "task_complete": false, "task_failed": false}, "errors": [], "warnings": []} to /topic/public.worker.event
ERROR:blueapi.worker.reworker:'sample_stage.x' does not match any of the regexes: '^([^./]+)$'

Failed validating 'additionalProperties' in schema['patternProperties']['^([^./]+)$']['patternProperties']['^([^./]+)$']:
    {'additionalProperties': False,
     'patternProperties': {'^([^./]+)$': {'$ref': '#/definitions/DataType'}},
     'title': 'DataType'}

On instance['plan_args']['axes_to_move']:
    {'sample_stage.x': "EpicsMotor(prefix='BL49P-MO-MAP-01:STAGE:X', "
                       "name='sample_stage_x', parent='sample_stage', "
                       'settle_time=0.0, timeout=None, '
                       "read_attrs=['user_readback', 'user_setpoint'], "
                       "configuration_attrs=['user_offset', "
                       "'user_offset_dir', 'velocity', 'acceleration', "
                       "'motor_egu'])"}
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/blueapi/worker/reworker.py", line 235, in _cycle
    self._current.task.do_task(self._ctx)
  File "/venv/lib/python3.11/site-packages/blueapi/worker/task.py", line 33, in do_task
    ctx.run_engine(wrapped_plan_generator)
  File "/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 903, in __call__
    plan_return = self._resume_task(init_func=_build_task)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1042, in _resume_task
    raise exc
  File "/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1672, in _run
    raise err
  File "/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1532, in _run
    msg = self._plan_stack[-1].send(resp)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/blueapi/core/context.py", line 76, in wrap
    yield from wrapped_plan
  File "/venv/lib/python3.11/site-packages/blueapi/preprocessors/attach_metadata.py", line 36, in attach_metadata
    yield from bpp.inject_md_wrapper(
  File "/venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 752, in inject_md_wrapper
    return (yield from msg_mutator(plan, _inject_md))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 263, in msg_mutator
    msg = plan.send(_s)
          ^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/dls_bluesky_core/plans/scanspec.py", line 57, in scan
    yield from bp.scan_nd(detectors, cycler, md=_md)
  File "/venv/lib/python3.11/site-packages/bluesky/plans.py", line 1015, in scan_nd
    return (yield from inner_scan_nd())
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/utils/__init__.py", line 1203, in dec_inner
    return (yield from plan)
            ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 985, in stage_wrapper
    return (yield from finalize_wrapper(inner(), unstage_devices()))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 535, in finalize_wrapper
    ret = yield from plan
          ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 983, in inner
    return (yield from plan)
            ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/utils/__init__.py", line 1203, in dec_inner
    return (yield from plan)
            ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 343, in run_wrapper
    rs_uid = yield from open_run(md)
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/plan_stubs.py", line 961, in open_run
    return (yield Msg('open_run', **(md or {})))
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/preprocessors.py", line 251, in msg_mutator
    _s = yield msg
         ^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1592, in _run
    new_response = await coro(msg)
                   ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 1787, in _open_run
    new_uid = await current_run.open_run(msg)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/bundlers.py", line 72, in open_run
    run = compose_run(uid=self._run_start_uid, event_counters=self._sequence_counters, metadata=self._md)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/event_model/__init__.py", line 2606, in compose_run
    schema_validators[DocumentNames.start].validate(doc)
  File "/venv/lib/python3.11/site-packages/jsonschema/validators.py", line 435, in validate
    raise error
jsonschema.exceptions.ValidationError: 'sample_stage.x' does not match any of the regexes: '^([^./]+)$'

Failed validating 'additionalProperties' in schema['patternProperties']['^([^./]+)$']['patternProperties']['^([^./]+)$']:
    {'additionalProperties': False,
     'patternProperties': {'^([^./]+)$': {'$ref': '#/definitions/DataType'}},
     'title': 'DataType'}

On instance['plan_args']['axes_to_move']:
    {'sample_stage.x': "EpicsMotor(prefix='BL49P-MO-MAP-01:STAGE:X', "
                       "name='sample_stage_x', parent='sample_stage', "
                       'settle_time=0.0, timeout=None, '
                       "read_attrs=['user_readback', 'user_setpoint'], "
                       "configuration_attrs=['user_offset', "
                       "'user_offset_dir', 'velocity', 'acceleration', "
                       "'motor_egu'])"}
INFO:blueapi.messaging.stomptemplate:SENDING {"state": "IDLE", "task_status": {"task_id": "8c7fc10c-c4f9-4423-8bd1-15544f63f473", "task_complete": true, "task_failed": true}, "errors": ["'sample_stage.x' does not match any of the regexes: '^([^./]+)$'\n\nFailed validating 'additionalProperties' in schema['patternProperties']['^([^./]+)$']['patternProperties']['^([^./]+)$']:\n    {'additionalProperties': False,\n     'patternProperties': {'^([^./]+)$': {'$ref': '#/definitions/DataType'}},\n     'title': 'DataType'}\n\nOn instance['plan_args']['axes_to_move']:\n    {'sample_stage.x': \"EpicsMotor(prefix='BL49P-MO-MAP-01:STAGE:X', \"\n                       \"name='sample_stage_x', parent='sample_stage', \"\n                       'settle_time=0.0, timeout=None, '\n                       \"read_attrs=['user_readback', 'user_setpoint'], \"\n                       \"configuration_attrs=['user_offset', \"\n                       \"'user_offset_dir', 'velocity', 'acceleration', \"\n                       \"'motor_egu'])\"}"], "warnings": []} to /topic/public.worker.event
INFO:blueapi.worker.reworker:Awaiting task
```

From running command:
```shell
blueapi -c config/p49-client.yaml controller run scan '{"detectors": ["det"], "spec": {"type": "Line", "axis": "sample_stage.x", "start": 0, "stop": 1, "num": 5}, "axes_to_move": {"sample_stage.x": "sample_stage.x"}}'
```

**Comment by DiamondJoseph** [comment]
This is being tracked internally as DAQ-5092

**Comment by ZohebShaikh** [comment]
Unable to replicate: p49 was deployed with **p49.py** attached below:-
```
from dodal.beamlines.beamline_utils import device_instantiation
from dodal.beamlines.beamline_utils import set_beamline as set_utils_beamline
from dodal.devices.areadetector import AdAravisDetector
from dodal.devices.htss import HTSSTomoStage
from dodal.log import set_beamline as set_log_beamline
from dodal.utils import get_beamline_name
#from ophyd import EpicsMotor
from ophyd_async.epics.motion import Motor

BL = get_beamline_name("p49")
set_log_beamline(BL)
set_utils_beamline(BL)

def x(
    wait_for_connection: bool = True, fake_with_ophyd_sim: bool = False
) -> Motor:
    return device_instantiation(
        Motor,
        "sample_x",
        "-MO-MAP-01:STAGE:X",
        wait_for_connection,
        fake_with_ophyd_sim,
    )

def theta(
    wait_for_connection: bool = True, fake_with_ophyd_sim: bool = False
) -> Motor:
    return device_instantiation(
        Motor,
        "sample_theta",
        "-MO-MAP-01:STAGE:A",
        wait_for_connection,
        fake_with_ophyd_sim,
    )


# def sample(
#     wait_for_connection: bool = True, fake_with_ophyd_sim: bool = False
# ) -> HTSSTomoStage:
#     return device_instantiation(
#         HTSSTomoStage,
#         "sample_stage",
#         "-MO-MAP-01:",
#         wait_for_connection,
#         fake_with_ophyd_sim,
#     )

def det(
    wait_for_connection: bool = True, fake_with_ophyd_sim: bool = False
) -> AdAravisDetector:
    det = device_instantiation(
        AdAravisDetector,
        "det",
        "-EA-DET-01:",
        wait_for_connection,
        fake_with_ophyd_sim,
    )
    det.read_attrs += ["cam"]
    det.cam.read_attrs += ["acquire_time", "acquire_period"]
    det.hdf.reg_root = "/exports/mybeamline/data"
    det.hdf.write_path_template = "%Y"
    return det
```
dodal module, with devices sample_x and sample_theta: sample_stage commented out because not same series of axes as p45. When run up in dummy mode with p45 sample stage, blueapi was able to get child devices from their fields.
