### ISSUE TITLE
Numpy array not serializable

### ISSUE THREAD

**Issue by DominicOram** [DiamondLightSource/blueapi#578]
When trying to monitor a PV with type `NDArray[np.uint8]` `blueAPI` gives me the following error and the data does not get passed to my own callback.
```
ERROR:p4p.client.asyncio:Error processing Subscription event: Value(array([255, 255, 255, ..., 159, 156, 154], dtype=uint8))
Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/p4p/client/asyncio.py", line 383, in _handle
    await self._cb(E)
  File "/venv/lib/python3.11/site-packages/ophyd_async/epics/_backend/_p4p.py", line 405, in async_callback
    callback(self.converter.reading(v), self.converter.value(v))
  File "/venv/lib/python3.11/site-packages/ophyd_async/core/signal.py", line 138, in _callback
    self._notify(function, want_value)
  File "/venv/lib/python3.11/site-packages/ophyd_async/core/signal.py", line 144, in _notify
    function({self._signal.name: self._reading})
  File "/venv/lib/python3.11/site-packages/bluesky/bundlers.py", line 416, in emit_event
    self.emit_sync(DocumentNames.event, doc)
  File "/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 2569, in emit_sync
    self.dispatcher.process(name, doc)
  File "/venv/lib/python3.11/site-packages/bluesky/run_engine.py", line 2592, in process
    exceptions = self.cb_registry.process(name, name.name, doc)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/bluesky/utils/__init__.py", line 385, in process
    func(*args, **kwargs)
  File "/venv/lib/python3.11/site-packages/bluesky/utils/__init__.py", line 474, in __call__
    return mtd(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/blueapi/worker/reworker.py", line 328, in _on_document
    self._data_events.publish(
  File "/venv/lib/python3.11/site-packages/blueapi/core/event.py", line 80, in publish
    callback(event, correlation_id)
  File "/venv/lib/python3.11/site-packages/blueapi/service/handler.py", line 83, in forward_message
    self._messaging_template.send(destination, event, None, correlation_id)
  File "/venv/lib/python3.11/site-packages/blueapi/messaging/stomptemplate.py", line 125, in send
    destination, json.dumps(serialize(obj)), on_reply, correlation_id
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ndarray is not JSON serializable
```

**Comment by callumforrester** [comment]
We will need to add handling for numpy arrays in the message serialization. Currently we use `json.dumps` [here](https://github.com/DiamondLightSource/blueapi/blob/0a4abfe67423145db6bfca7fd8e68e46d482f28c/src/blueapi/messaging/stomptemplate.py#L125), which does not support numpy. We could change it to use [orjson](https://github.com/ijl/orjson) instead, which does support numpy...

**Comment by DominicOram** [comment]
Great, thanks. I need this ASAP for beamline testing Friday so I will probably pick it up. Maybe a different issue but how would you feel about guarding this so that a failure to serialize in stomp does not cause the event to be swallowed up? The reason this issue is a blocker on the beamline is not because I need the `stomp` serialization but because I need my other callbacks to be able to see the event
